### ISSUE TITLE
updated to jekyll 2.5.1 - getting error: undefined method 'each' for nil:NilClass

### ISSUE THREAD

**Issue by JasonSwingen** [juthilo/run-jekyll-on-windows#49]
jekyll version: 2.5.1
ruby version: 2.0.0p576

> jekyll serve --trace 
Configuration file: C:/Users/Jason/Documents/GitHub/JasonSwingen.github.io/_config.yml
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:27:in `require_gems': undefined method `each' for nil:NilClass (NoMethodError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/site.rb:79:in `setup'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/site.rb:41:in `initialize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:29:in `new'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:29:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.1/bin/jekyll:20:in `<top (required)>'
        from C:/Ruby200-x64/bin/jekyll:22:in `load'
        from C:/Ruby200-x64/bin/jekyll:22:in `<main>'

**Comment by jpdevries** [comment]
Me too
jekyll 3.3.1
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
OS X 10.12.2
